const boards = [
  { id: "arrivals", name: "Я здесь впервые" },
  { id: "routes", name: "Пути и уровни" },
  { id: "signals", name: "Сигналы" },
  { id: "lost", name: "Пропавшие" },
  { id: "warnings", name: "Предупреждения" },
  { id: "off", name: "Off-topic" }
];

const threads = {
  arrivals: [
  { user:"unknown", time:"??:??", text:"я не помню момент, когда перешёл по ссылке" },
  { user:"unknown", time:"—", text:"адрес изменился уже после загрузки страницы" },
  { user:"wanderer_17", time:"ночью", text:"я просто искал старый форум, но оказался здесь" },
  { user:"unknown", time:"архив", text:"это точно не тот сайт, который я открывал" },
  { user:"unknown", time:"03:14", text:"кнопка назад не работает" },
  { user:"unknown", time:"—", text:"я закрыл вкладку и снова увидел этот форум" },
  { user:"unknown", time:"??:??", text:"я не вводил логин, но профиль уже был" },
  { user:"unknown", time:"ночью", text:"страница открылась сама" },
  { user:"unknown", time:"—", text:"почему здесь так тихо" },
  { user:"unknown", time:"архив", text:"форум выглядит давно заброшенным" },

  { user:"unknown", time:"??:??", text:"я думал, что это ошибка браузера" },
  { user:"unknown", time:"—", text:"но адрес снова тот же" },
  { user:"wanderer_17", time:"архив", text:"раньше здесь отвечали быстрее" },
  { user:"unknown", time:"ночью", text:"я не уверен, что хотел зайти так глубоко" },
  { user:"unknown", time:"03:22", text:"страница не закрывается" },
  { user:"unknown", time:"—", text:"кто-нибудь вообще читает это" },
  { user:"unknown", time:"??:??", text:"я здесь впервые" },
  { user:"unknown", time:"—", text:"и надеюсь, что в последний раз" },
  { user:"unknown", time:"архив", text:"нет приветственного сообщения" },
  { user:"unknown", time:"ночью", text:"но есть старые следы" },

  { user:"unknown", time:"??:??", text:"ссылка была внутри старого сообщения" },
  { user:"unknown", time:"—", text:"я не искал этот форум напрямую" },
  { user:"unknown", time:"03:41", text:"адресная строка дрожала" },
  { user:"unknown", time:"—", text:"это место ощущается неправильным" },
  { user:"unknown", time:"архив", text:"дата регистрации пуста" },
  { user:"unknown", time:"ночью", text:"профиль уже существовал" },
  { user:"unknown", time:"—", text:"я не помню, чтобы создавал его" },
  { user:"unknown", time:"??:??", text:"но он здесь" },
  { user:"unknown", time:"архив", text:"время последнего входа не указано" },
  { user:"unknown", time:"—", text:"как будто я уже был здесь раньше" },

  { user:"unknown", time:"??:??", text:"я нажал обновить, но ничего не изменилось" },
  { user:"unknown", time:"—", text:"страница загрузилась слишком быстро" },
  { user:"wanderer_17", time:"архив", text:"раньше мы предупреждали новичков" },
  { user:"unknown", time:"ночью", text:"но сейчас никто не отвечает" },
  { user:"unknown", time:"—", text:"форум не выглядит живым" },
  { user:"unknown", time:"03:03", text:"но сообщения есть" },
  { user:"unknown", time:"—", text:"они просто старые" },
  { user:"unknown", time:"архив", text:"очень старые" },
  { user:"unknown", time:"??:??", text:"я не понимаю, как сюда выйти" },
  { user:"unknown", time:"—", text:"кнопка выхода ведёт назад" },

  { user:"unknown", time:"??:??", text:"я думал, что это чей-то розыгрыш" },
  { user:"unknown", time:"—", text:"но слишком много совпадений" },
  { user:"unknown", time:"ночью", text:"форум открылся без предупреждения" },
  { user:"unknown", time:"архив", text:"нет правил" },
  { user:"unknown", time:"—", text:"нет модераторов" },
  { user:"unknown", time:"03:17", text:"но есть структура" },
  { user:"unknown", time:"—", text:"как будто кто-то ожидал гостей" },
  { user:"unknown", time:"архив", text:"я не уверен, что мы здесь желанные" },
  { user:"unknown", time:"??:??", text:"я чувствую, что меня заметили" },
  { user:"unknown", time:"—", text:"и это пугает" },

  { user:"unknown", time:"??:??", text:"я хотел закрыть сайт" },
  { user:"unknown", time:"—", text:"но решил прочитать ещё" },
  { user:"unknown", time:"ночью", text:"это было ошибкой" },
  { user:"unknown", time:"архив", text:"если кто-то это читает" },
  { user:"unknown", time:"—", text:"ответьте" },
  { user:"unknown", time:"??:??", text:"я здесь впервые" },
  { user:"unknown", time:"—", text:"и не знаю, что делать дальше" }
],
  routes: [
  { user:"nullpath", time:"архив", text:"пути здесь не ведут туда, куда обещают" },
  { user:"unknown", time:"??:??", text:"адрес меняется после загрузки" },
  { user:"unknown", time:"—", text:"я пытался сохранить ссылку, но она стала другой" },
  { user:"unknown", time:"03:11", text:"маршрут совпал только с первого раза" },
  { user:"unknown", time:"ночью", text:"переход исчез после обновления" },
  { user:"nullpath", time:"архив", text:"если пройти по ссылке дважды, результат разный" },
  { user:"unknown", time:"—", text:"карта не совпадает с реальностью" },
  { user:"unknown", time:"??:??", text:"некоторые пути существуют только ночью" },
  { user:"unknown", time:"архив", text:"я не смог вернуться тем же маршрутом" },
  { user:"unknown", time:"—", text:"кнопка назад ведёт в другой раздел" },

  { user:"unknown", time:"03:27", text:"адрес не имеет домена" },
  { user:"unknown", time:"—", text:"строка выглядит обрезанной" },
  { user:"nullpath", time:"архив", text:"есть уровни между страницами" },
  { user:"unknown", time:"??:??", text:"я заметил переход без названия" },
  { user:"unknown", time:"ночью", text:"он появился сам" },
  { user:"unknown", time:"—", text:"я не нажимал ссылку" },
  { user:"unknown", time:"архив", text:"но оказался в другом месте" },
  { user:"unknown", time:"03:02", text:"путь не фиксируется в истории" },
  { user:"unknown", time:"—", text:"браузер его не помнит" },
  { user:"unknown", time:"архив", text:"но форум — да" },

  { user:"nullpath", time:"архив", text:"некоторые маршруты возвращают сюда намеренно" },
  { user:"unknown", time:"??:??", text:"я пытался выйти через внешний сайт" },
  { user:"unknown", time:"—", text:"но оказался глубже" },
  { user:"unknown", time:"ночью", text:"адрес выглядел знакомым" },
  { user:"unknown", time:"архив", text:"но я никогда его не посещал" },
  { user:"unknown", time:"—", text:"уровни не имеют нумерации" },
  { user:"unknown", time:"03:33", text:"я считал переходы, но сбился" },
  { user:"unknown", time:"—", text:"один из них повторился" },
  { user:"unknown", time:"архив", text:"точно такой же" },
  { user:"unknown", time:"—", text:"или мне показалось" },

  { user:"nullpath", time:"архив", text:"есть маршруты, которые нельзя описать словами" },
  { user:"unknown", time:"??:??", text:"я попробовал скопировать путь" },
  { user:"unknown", time:"—", text:"вставка привела в другое место" },
  { user:"unknown", time:"ночью", text:"иногда ссылка ведёт не сразу" },
  { user:"unknown", time:"архив", text:"как будто ждёт" },
  { user:"unknown", time:"—", text:"чего именно — не знаю" },
  { user:"unknown", time:"03:48", text:"путь активировался без клика" },
  { user:"unknown", time:"—", text:"экран просто сменился" },
  { user:"unknown", time:"архив", text:"в этот момент звук пропал" },
  { user:"unknown", time:"—", text:"я это заметил" },

  { user:"nullpath", time:"архив", text:"если задержаться на уровне, он меняется" },
  { user:"unknown", time:"??:??", text:"интерфейс стал проще" },
  { user:"unknown", time:"—", text:"как будто дальше не предусмотрено" },
  { user:"unknown", time:"ночью", text:"путь назад был заблокирован" },
  { user:"unknown", time:"архив", text:"без объяснения" },
  { user:"unknown", time:"—", text:"кнопки остались" },
  { user:"unknown", time:"03:09", text:"но они вели в одно и то же место" },
  { user:"unknown", time:"—", text:"я проверил" },
  { user:"unknown", time:"архив", text:"несколько раз" },
  { user:"unknown", time:"—", text:"результат не изменился" },

  { user:"nullpath", time:"архив", text:"некоторые маршруты реагируют на внимание" },
  { user:"unknown", time:"??:??", text:"когда я долго смотрю на ссылку" },
  { user:"unknown", time:"—", text:"она меняется" },
  { user:"unknown", time:"ночью", text:"один путь исчез, когда я попытался вернуться" },
  { user:"unknown", time:"архив", text:"как будто его не должно было быть" },
  { user:"unknown", time:"—", text:"но я точно там был" },
  { user:"unknown", time:"03:56", text:"уровень был пустым" },
  { user:"unknown", time:"—", text:"без текста" },
  { user:"unknown", time:"архив", text:"без ссылок" },
  { user:"unknown", time:"—", text:"я пробыл там недолго" },

  { user:"unknown", time:"??:??", text:"я не уверен, что все пути здесь случайны" },
  { user:"unknown", time:"—", text:"некоторые выглядят направленными" },
  { user:"unknown", time:"ночью", text:"как будто кто-то рассчитывал маршрут" },
  { user:"unknown", time:"архив", text:"для конкретного пользователя" },
  { user:"unknown", time:"—", text:"я не уверен, что это был я" },
  { user:"unknown", time:"03:17", text:"путь оборвался без причины" },
  { user:"unknown", time:"—", text:"страница осталась" },
  { user:"unknown", time:"архив", text:"но содержимое исчезло" },
  { user:"unknown", time:"—", text:"я не смог повторить переход" },
  { user:"unknown", time:"—", text:"и, возможно, это к лучшему" }
],
  signals: [
  { user:"unknown", time:"ночью", text:"мне пришло уведомление, но без текста" },
  { user:"unknown", time:"—", text:"отправитель не указан" },
  { user:"unknown", time:"03:12", text:"я получил ответ, хотя ничего не писал" },
  { user:"unknown", time:"архив", text:"уведомление появилось после закрытия вкладки" },
  { user:"unknown", time:"—", text:"браузер был выключен" },
  { user:"unknown", time:"ночью", text:"экран мигнул и показал сообщение" },
  { user:"unknown", time:"—", text:"оно исчезло сразу" },
  { user:"unknown", time:"архив", text:"в журнале событий ничего нет" },
  { user:"unknown", time:"??:??", text:"но я уверен, что видел его" },
  { user:"unknown", time:"—", text:"оно было адресовано мне" },

  { user:"unknown", time:"03:27", text:"мне пришёл ответ без вопроса" },
  { user:"unknown", time:"—", text:"я не понимаю, на что он отвечал" },
  { user:"unknown", time:"ночью", text:"уведомление появилось на секунду" },
  { user:"unknown", time:"архив", text:"я не успел прочитать всё" },
  { user:"unknown", time:"—", text:"но запомнил ощущение" },
  { user:"unknown", time:"??:??", text:"как будто кто-то проверял связь" },
  { user:"unknown", time:"—", text:"не со мной" },
  { user:"unknown", time:"архив", text:"а через меня" },
  { user:"unknown", time:"—", text:"это странно формулировать" },
  { user:"unknown", time:"—", text:"но другого объяснения нет" },

  { user:"unknown", time:"ночью", text:"я услышал звук уведомления" },
  { user:"unknown", time:"—", text:"хотя звук был выключен" },
  { user:"unknown", time:"03:41", text:"сообщение пришло из этого же форума" },
  { user:"unknown", time:"—", text:"но тема не существовала" },
  { user:"unknown", time:"архив", text:"при переходе она исчезла" },
  { user:"unknown", time:"—", text:"как будто её никогда не было" },
  { user:"unknown", time:"??:??", text:"я проверил историю уведомлений" },
  { user:"unknown", time:"—", text:"там пусто" },
  { user:"unknown", time:"архив", text:"но отметка о доставке есть" },
  { user:"unknown", time:"—", text:"дата указана неверно" },

  { user:"unknown", time:"ночью", text:"мне пришло сообщение без символов" },
  { user:"unknown", time:"—", text:"пустое, но прочитанное" },
  { user:"unknown", time:"архив", text:"статус был «доставлено»" },
  { user:"unknown", time:"—", text:"кому — не указано" },
  { user:"unknown", time:"03:05", text:"после этого интерфейс стал другим" },
  { user:"unknown", time:"—", text:"на несколько секунд" },
  { user:"unknown", time:"архив", text:"как будто система ожидала реакции" },
  { user:"unknown", time:"—", text:"я ничего не сделал" },
  { user:"unknown", time:"??:??", text:"но сигнал пропал" },
  { user:"unknown", time:"—", text:"оставив ощущение задержки" },

  { user:"unknown", time:"ночью", text:"уведомление пришло дважды" },
  { user:"unknown", time:"—", text:"с разницей в секунду" },
  { user:"unknown", time:"архив", text:"второе было искажено" },
  { user:"unknown", time:"—", text:"часть символов отсутствовала" },
  { user:"unknown", time:"03:33", text:"я не смог его скопировать" },
  { user:"unknown", time:"—", text:"выделение не работало" },
  { user:"unknown", time:"архив", text:"как будто текст не предназначался для чтения" },
  { user:"unknown", time:"—", text:"только для фиксации" },
  { user:"unknown", time:"??:??", text:"я почувствовал, что его заметили" },
  { user:"unknown", time:"—", text:"не меня" },

  { user:"unknown", time:"ночью", text:"мне показалось, что сигнал был адресным" },
  { user:"unknown", time:"—", text:"как будто он знал, что я здесь" },
  { user:"unknown", time:"архив", text:"сообщение появилось, когда я перестал читать" },
  { user:"unknown", time:"—", text:"и собирался закрыть сайт" },
  { user:"unknown", time:"03:19", text:"после этого вкладка снова открылась" },
  { user:"unknown", time:"—", text:"сама" },
  { user:"unknown", time:"архив", text:"уведомление больше не повторялось" },
  { user:"unknown", time:"—", text:"как будто проверка завершилась" },
  { user:"unknown", time:"??:??", text:"я не уверен, что хочу ещё сигналы" },
  { user:"unknown", time:"—", text:"но они продолжаются" }
],
  lost: [
  { user:"system", time:"архив", text:"user_12 — последнее появление зафиксировано" },
  { user:"unknown", time:"—", text:"кто-нибудь видел его после этого" },
  { user:"system", time:"архив", text:"ответов не поступало" },
  { user:"unknown", time:"ночью", text:"он писал здесь почти каждый день" },
  { user:"unknown", time:"—", text:"а потом просто исчез" },
  { user:"system", time:"архив", text:"аккаунт помечен как неактивный" },
  { user:"unknown", time:"—", text:"но профиль остался" },
  { user:"unknown", time:"03:14", text:"последнее сообщение было странным" },
  { user:"unknown", time:"—", text:"как будто он знал" },
  { user:"unknown", time:"—", text:"что это последнее" },

  { user:"system", time:"архив", text:"wanderer_09 — сессия не завершена" },
  { user:"unknown", time:"—", text:"он искал путь назад" },
  { user:"unknown", time:"ночью", text:"писал, что почти нашёл выход" },
  { user:"system", time:"архив", text:"соединение прервано" },
  { user:"unknown", time:"—", text:"после этого тишина" },
  { user:"unknown", time:"архив", text:"я пытался ему написать" },
  { user:"unknown", time:"—", text:"сообщение доставлено" },
  { user:"unknown", time:"—", text:"ответа нет" },
  { user:"unknown", time:"—", text:"уже давно" },
  { user:"unknown", time:"—", text:"слишком давно" },

  { user:"system", time:"архив", text:"alice — последнее появление не зафиксировано" },
  { user:"unknown", time:"—", text:"она была здесь раньше других" },
  { user:"unknown", time:"ночью", text:"писала спокойно" },
  { user:"unknown", time:"—", text:"как будто знала правила" },
  { user:"unknown", time:"архив", text:"потом перестала отвечать" },
  { user:"unknown", time:"—", text:"даже на прямые вопросы" },
  { user:"unknown", time:"—", text:"её профиль не удалён" },
  { user:"system", time:"архив", text:"статус: не определён" },
  { user:"unknown", time:"—", text:"что это вообще значит" },
  { user:"unknown", time:"—", text:"мы так и не поняли" },

  { user:"system", time:"архив", text:"echo_04 — активность прекращена" },
  { user:"unknown", time:"—", text:"он отвечал только на сигналы" },
  { user:"unknown", time:"ночью", text:"говорил, что слышит эхо" },
  { user:"unknown", time:"—", text:"а потом пропал" },
  { user:"system", time:"архив", text:"последний вход: неизвестно" },
  { user:"unknown", time:"—", text:"как можно не знать время входа" },
  { user:"unknown", time:"—", text:"но система так пишет" },
  { user:"unknown", time:"—", text:"и это пугает" },
  { user:"unknown", time:"—", text:"больше всего" },
  { user:"unknown", time:"—", text:"что система не уверена" },

  { user:"system", time:"архив", text:"user_31 — профиль повреждён" },
  { user:"unknown", time:"—", text:"он спрашивал про уровни" },
  { user:"unknown", time:"ночью", text:"очень настойчиво" },
  { user:"unknown", time:"—", text:"будто торопился" },
  { user:"system", time:"архив", text:"последнее сообщение не сохранено" },
  { user:"unknown", time:"—", text:"я читал его" },
  { user:"unknown", time:"—", text:"оно исчезло" },
  { user:"unknown", time:"—", text:"как будто его вырезали" },
  { user:"unknown", time:"—", text:"из истории" },
  { user:"unknown", time:"—", text:"вместе с ним" },

  { user:"system", time:"архив", text:"nullpath — статус неизвестен" },
  { user:"unknown", time:"—", text:"он знал больше остальных" },
  { user:"unknown", time:"ночью", text:"писал про маршруты" },
  { user:"unknown", time:"—", text:"которые не стоит описывать" },
  { user:"system", time:"архив", text:"последний лог противоречив" },
  { user:"unknown", time:"—", text:"что это значит" },
  { user:"unknown", time:"—", text:"противоречив" },
  { user:"unknown", time:"—", text:"между чем и чем" },
  { user:"unknown", time:"—", text:"он не успел объяснить" },
  { user:"unknown", time:"—", text:"или не захотел" },

  { user:"system", time:"архив", text:"несколько аккаунтов помечены как отсутствующие" },
  { user:"unknown", time:"—", text:"их имена больше не открываются" },
  { user:"unknown", time:"ночью", text:"ссылки ведут в пустоту" },
  { user:"unknown", time:"—", text:"иногда страница моргает" },
  { user:"unknown", time:"—", text:"и всё" },
  { user:"system", time:"архив", text:"восстановление невозможно" },
  { user:"unknown", time:"—", text:"система даже не пытается" },
  { user:"unknown", time:"—", text:"как будто знает результат" },
  { user:"unknown", time:"—", text:"мы тоже начинаем понимать" },
  { user:"unknown", time:"—", text:"но не хотим" }
],
  warnings: [
  { user:"unknown", time:"—", text:"если ты здесь впервые, не читай всё подряд" },
  { user:"unknown", time:"—", text:"лучше закрой сайт сейчас" },
  { user:"unknown", time:"архив", text:"мы уже пытались предупредить новичков" },
  { user:"unknown", time:"—", text:"не задерживайся здесь надолго" },
  { user:"unknown", time:"—", text:"чем дольше читаешь, тем сложнее выйти" },
  { user:"unknown", time:"архив", text:"это не метафора" },
  { user:"unknown", time:"—", text:"мы проверяли" },
  { user:"unknown", time:"—", text:"несколько раз" },
  { user:"unknown", time:"—", text:"результат всегда одинаковый" },
  { user:"unknown", time:"—", text:"кто-то остаётся" },

  { user:"unknown", time:"—", text:"не обновляй страницу слишком часто" },
  { user:"unknown", time:"архив", text:"это сбивает ориентацию" },
  { user:"unknown", time:"—", text:"если адрес изменился, не пытайся его запомнить" },
  { user:"unknown", time:"—", text:"он не повторится" },
  { user:"unknown", time:"—", text:"и это хорошо" },
  { user:"unknown", time:"архив", text:"хуже, если повторится" },
  { user:"unknown", time:"—", text:"значит, ты застрял" },
  { user:"unknown", time:"—", text:"и форум это понял" },
  { user:"unknown", time:"—", text:"раньше этого не было" },
  { user:"unknown", time:"—", text:"раньше мы могли уйти" },

  { user:"unknown", time:"—", text:"не отвечай на сигналы" },
  { user:"unknown", time:"архив", text:"даже если кажется, что сообщение адресовано тебе" },
  { user:"unknown", time:"—", text:"особенно тогда" },
  { user:"unknown", time:"—", text:"ответ фиксируется" },
  { user:"unknown", time:"—", text:"мы не знаем где" },
  { user:"unknown", time:"—", text:"но он остаётся" },
  { user:"unknown", time:"архив", text:"после этого всё меняется" },
  { user:"unknown", time:"—", text:"интерфейс" },
  { user:"unknown", time:"—", text:"пути" },
  { user:"unknown", time:"—", text:"ты сам" },

  { user:"unknown", time:"—", text:"если видишь пустую страницу — не жди" },
  { user:"unknown", time:"архив", text:"это не ошибка загрузки" },
  { user:"unknown", time:"—", text:"это пауза" },
  { user:"unknown", time:"—", text:"форум ждёт" },
  { user:"unknown", time:"—", text:"чего именно — мы не выяснили" },
  { user:"unknown", time:"архив", text:"но ожидание всегда заканчивается" },
  { user:"unknown", time:"—", text:"не в пользу пользователя" },
  { user:"unknown", time:"—", text:"мы проверяли" },
  { user:"unknown", time:"—", text:"остальные не успели написать" },
  { user:"unknown", time:"—", text:"почему" },

  { user:"unknown", time:"—", text:"не пытайся помочь пропавшим" },
  { user:"unknown", time:"архив", text:"это не работает" },
  { user:"unknown", time:"—", text:"мы пробовали искать" },
  { user:"unknown", time:"—", text:"писать" },
  { user:"unknown", time:"—", text:"отвечать за них" },
  { user:"unknown", time:"архив", text:"после этого исчезли ещё двое" },
  { user:"unknown", time:"—", text:"совпадение или нет" },
  { user:"unknown", time:"—", text:"мы не знаем" },
  { user:"unknown", time:"—", text:"но больше не рискуем" },
  { user:"unknown", time:"—", text:"если это вообще риск" },

  { user:"unknown", time:"—", text:"если тебе кажется, что форум обращается к тебе" },
  { user:"unknown", time:"архив", text:"это плохой знак" },
  { user:"unknown", time:"—", text:"раньше он был безличным" },
  { user:"unknown", time:"—", text:"сейчас нет" },
  { user:"unknown", time:"—", text:"мы не уверены, когда это изменилось" },
  { user:"unknown", time:"архив", text:"возможно, после alice" },
  { user:"unknown", time:"—", text:"её имя лучше не писать" },
  { user:"unknown", time:"—", text:"даже здесь" },
  { user:"unknown", time:"—", text:"на всякий случай" },
  { user:"unknown", time:"—", text:"хотя, возможно, уже поздно" },

  { user:"unknown", time:"—", text:"если ты всё ещё читаешь это" },
  { user:"unknown", time:"архив", text:"значит, предыдущие предупреждения не сработали" },
  { user:"unknown", time:"—", text:"мы не знаем, что сказать дальше" },
  { user:"unknown", time:"—", text:"у нас не осталось новых советов" },
  { user:"unknown", time:"—", text:"только повторения" },
  { user:"unknown", time:"архив", text:"повторения — плохой знак" },
  { user:"unknown", time:"—", text:"они означают замкнутый путь" },
  { user:"unknown", time:"—", text:"или его отсутствие" },
  { user:"unknown", time:"—", text:"если найдёшь выход" },
  { user:"unknown", time:"—", text:"не возвращайся" }
],
  off: [
  { user:"unknown", time:"—", text:"я здесь" },
  { user:"unknown", time:"—", text:"я здесь" },
  { user:"unknown", time:"—", text:"я здесь" },
  { user:"unknown", time:"—", text:"почему текст повторяется" },
  { user:"unknown", time:"—", text:"это уже было" },
  { user:"unknown", time:"—", text:"я видел это выше" },
  { user:"unknown", time:"—", text:"или ниже" },
  { user:"unknown", time:"—", text:"или раньше" },
  { user:"unknown", time:"—", text:"время здесь не работает" },
  { user:"unknown", time:"—", text:"я не уверен" },

  { user:"unknown", time:"—", text:"слово потеряло смысл" },
  { user:"unknown", time:"—", text:"смысл потерял слово" },
  { user:"unknown", time:"—", text:"текст пишет себя" },
  { user:"unknown", time:"—", text:"я не писал это" },
  { user:"unknown", time:"—", text:"но это написано" },
  { user:"unknown", time:"—", text:"кем" },
  { user:"unknown", time:"—", text:"кем" },
  { user:"unknown", time:"—", text:"кем" },
  { user:"unknown", time:"—", text:"ответ не требуется" },
  { user:"unknown", time:"—", text:"ответ не предусмотрен" },

  { user:"unknown", time:"—", text:"я начал читать с конца" },
  { user:"unknown", time:"—", text:"но конца нет" },
  { user:"unknown", time:"—", text:"есть только это" },
  { user:"unknown", time:"—", text:"и это" },
  { user:"unknown", time:"—", text:"и это тоже" },
  { user:"unknown", time:"—", text:"повтор — не ошибка" },
  { user:"unknown", time:"—", text:"повтор — признак" },
  { user:"unknown", time:"—", text:"признак чего" },
  { user:"unknown", time:"—", text:"не уточняется" },
  { user:"unknown", time:"—", text:"не нужно уточнять" },

  { user:"unknown", time:"—", text:"я попытался перестать читать" },
  { user:"unknown", time:"—", text:"глаза закрылись" },
  { user:"unknown", time:"—", text:"текст остался" },
  { user:"unknown", time:"—", text:"он не на экране" },
  { user:"unknown", time:"—", text:"он здесь" },
  { user:"unknown", time:"—", text:"ты тоже это чувствуешь" },
  { user:"unknown", time:"—", text:"не отвечай" },
  { user:"unknown", time:"—", text:"ответ фиксируется" },
  { user:"unknown", time:"—", text:"фиксация завершена" },
  { user:"unknown", time:"—", text:"зачем" },

  { user:"unknown", time:"—", text:"строки сместились" },
  { user:"unknown", time:"—", text:"абзацы перепутались" },
  { user:"unknown", time:"—", text:"смысл между ними" },
  { user:"unknown", time:"—", text:"или под ними" },
  { user:"unknown", time:"—", text:"или вместо" },
  { user:"unknown", time:"—", text:"это не язык" },
  { user:"unknown", time:"—", text:"это его остаток" },
  { user:"unknown", time:"—", text:"оболочка" },
  { user:"unknown", time:"—", text:"без содержимого" },
  { user:"unknown", time:"—", text:"без выхода" },

  { user:"unknown", time:"—", text:"я видел имя" },
  { user:"unknown", time:"—", text:"оно исчезло" },
  { user:"unknown", time:"—", text:"я не буду его писать" },
  { user:"unknown", time:"—", text:"даже здесь" },
  { user:"unknown", time:"—", text:"особенно здесь" },
  { user:"unknown", time:"—", text:"потому что" },
  { user:"unknown", time:"—", text:"потому что" },
  { user:"unknown", time:"—", text:"потому что" },
  { user:"unknown", time:"—", text:"причина утрачена" },
  { user:"unknown", time:"—", text:"но след остался" },

  { user:"unknown", time:"—", text:"я пролистал вниз" },
  { user:"unknown", time:"—", text:"но оказался выше" },
  { user:"unknown", time:"—", text:"я пролистал вверх" },
  { user:"unknown", time:"—", text:"и вернулся сюда" },
  { user:"unknown", time:"—", text:"это место зациклено" },
  { user:"unknown", time:"—", text:"или я" },
  { user:"unknown", time:"—", text:"разницы больше нет" },
  { user:"unknown", time:"—", text:"если ты читаешь это" },
  { user:"unknown", time:"—", text:"ты тоже часть цикла" },
  { user:"unknown", time:"—", text:"запись продолжается" }
];


  const users = {
  unknown: {
    status: "неизвестно",
    bio: "профиль повреждён или не был создан полностью"
  },

  wanderer_17: {
    status: "оффлайн",
    bio: "один из первых, кто зашёл слишком глубоко"
  },

  nullpath: {
    status: "—",
    bio: "описывал маршруты, которые больше не существуют"
  },

  system: {
    status: "архив",
    bio: "автоматическая запись форума"
  }
};
};
